### ISSUE TITLE
inputs of the model

### ISSUE THREAD

**Issue by lihao0214** [HaydenCaffrey/SIG-VC#2]
https://github.com/HaydenCaffrey/SIG-VC/blob/1222e16ef1d6b7dbab3b68b1f5b9271b66dcfb31/conversion/train.py#LL168C17-L168C17

The model has two inputs: bnf and speaker information. But there only has one bnf input. Is't correct? or I miss something.

**Comment by HaydenCaffrey** [comment]
Hi, "bnf" and "tar_spk_embd" in this line of code are the corresponding arguments of the two inputs.
