### ISSUE TITLE
代码流程

### ISSUE THREAD

**Issue by lihao0214** [HaydenCaffrey/SIG-VC#3]
https://github.com/HaydenCaffrey/SIG-VC/blob/1222e16ef1d6b7dbab3b68b1f5b9271b66dcfb31/conversion/fastspeech2.py#LL45C32-L45C32
你好，还有个问题想请教一下，这个地方文章上是BNF先和源说话人embedding特征cat到一起，然后再过prenet，这块是实现和论文不一致吗？

**Comment by HaydenCaffrey** [comment]
你好，代码中的self.prenet指的是论文中content encoder的一部分，并不是论文中的prenet。https://github.com/HaydenCaffrey/SIG-VC/blob/1222e16ef1d6b7dbab3b68b1f5b9271b66dcfb31/conversion/fastspeech2.py#LL69C1-L70C1
这里对应论文中的prenet。论文流程图中的名称为了方便阐述经过整理和修改，所以并不能和代码中的变量名直接一一对应。这里的实现和论文是一致的。

**Comment by lihao0214** [comment]
好的，感谢回答
